name: Actualizar datos

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: npm run update-data

      - name: Guardar cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar datos públicos"
